
@host = http://localhost:3000

@userEmail = test@draab.at
@userPassword = tester
@userId = 2
@userAccessToken = 63805ef999a9a3d19603eaac




### send password reset link

POST {{host}}/api/v1/auth/requestPasswordResetLink
content-type: application/json

{
    "email": "{{userEmail}}"
}





### reset password

# @prompt specialToken SpecialToken from email
POST {{host}}/api/v1/auth/resetPassword
content-type: application/json

{
    "userId": "{{userId}}",
    "specialToken": "{{specialToken}}",
    "password": "{{userPassword}}"
}




