/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuthenticationMethods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oidc/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["startOidcLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oidc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["completeOidcLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestMagicLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic-links/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["consumeMagicLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete: operations["logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateMe"];
        trace?: never;
    };
    "/cars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCars"];
        put?: never;
        post: operations["createCar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cars/{carId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carId: components["parameters"]["CarId"];
            };
            cookie?: never;
        };
        get: operations["getCar"];
        put?: never;
        post?: never;
        delete: operations["deleteCar"];
        options?: never;
        head?: never;
        patch: operations["updateCar"];
        trace?: never;
    };
    "/cars/{carId}/refuels": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carId: components["parameters"]["CarId"];
            };
            cookie?: never;
        };
        get: components["pathItems"]["CarExpenseCollection"]["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cars/{carId}/repairs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carId: components["parameters"]["CarId"];
            };
            cookie?: never;
        };
        get: components["pathItems"]["CarExpenseCollection"]["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cars/{carId}/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carId: components["parameters"]["CarId"];
            };
            cookie?: never;
        };
        get: components["pathItems"]["CarExpenseCollection"]["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refuels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: components["pathItems"]["ExpenseCollection"]["get"];
        put?: never;
        post: components["pathItems"]["RefuelCreate"]["post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refuels/{refuelId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                refuelId: components["parameters"]["RefuelId"];
            };
            cookie?: never;
        };
        get: components["pathItems"]["RefuelDetail"]["get"];
        put?: never;
        post?: never;
        delete: components["pathItems"]["RefuelDetail"]["delete"];
        options?: never;
        head?: never;
        patch: components["pathItems"]["RefuelDetail"]["patch"];
        trace?: never;
    };
    "/refuels/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: components["pathItems"]["StationSuggestions"]["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refuels/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRefuelChart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repairs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: components["pathItems"]["ExpenseCollection"]["get"];
        put?: never;
        post: components["pathItems"]["RepairCreate"]["post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repairs/{repairId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repairId: components["parameters"]["RepairId"];
            };
            cookie?: never;
        };
        get: components["pathItems"]["RepairDetail"]["get"];
        put?: never;
        post?: never;
        delete: components["pathItems"]["RepairDetail"]["delete"];
        options?: never;
        head?: never;
        patch: components["pathItems"]["RepairDetail"]["patch"];
        trace?: never;
    };
    "/repairs/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: components["pathItems"]["StationSuggestions"]["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: components["pathItems"]["ExpenseCollection"]["get"];
        put?: never;
        post: components["pathItems"]["TicketCreate"]["post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        get: components["pathItems"]["TicketDetail"]["get"];
        put?: never;
        post?: never;
        delete: components["pathItems"]["TicketDetail"]["delete"];
        options?: never;
        head?: never;
        patch: components["pathItems"]["TicketDetail"]["patch"];
        trace?: never;
    };
    "/tickets/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: components["pathItems"]["LocationSuggestions"]["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExpenseStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        UUID: string;
        Decimal: string;
        Error: {
            /** @example validation_failed */
            code: string;
            message: string;
            fields?: {
                [key: string]: string;
            };
        };
        Profile: {
            id: components["schemas"]["UUID"];
            /** Format: email */
            email: string;
            firstName: string;
            lastName: string;
        };
        ProfileUpdate: {
            /** Format: email */
            email?: string;
            firstName?: string;
            lastName?: string;
        };
        Session: {
            profile: components["schemas"]["Profile"];
        };
        AuthenticationMethods: {
            methods: ("magic_link" | "oidc")[];
        };
        MagicLinkRequest: {
            /** Format: email */
            email: string;
            /** Format: uri-reference */
            returnTo?: string;
        };
        CarInput: {
            type: string;
            make: string;
            name: string;
            /** @enum {string} */
            fuel: "other" | "diesel" | "gasoline" | "electric";
            /** Format: date */
            firstRegistration: string;
            licensePlate: string;
            fin?: string;
            /** @default true */
            isActive: boolean;
            /** Format: date */
            purchaseDate?: string | null;
            purchasePrice?: components["schemas"]["Decimal"];
        };
        CarUpdate: {
            type?: string;
            make?: string;
            name?: string;
            /** @enum {string} */
            fuel?: "other" | "diesel" | "gasoline" | "electric";
            /** Format: date */
            firstRegistration?: string;
            licensePlate?: string;
            fin?: string;
            isActive?: boolean;
            /** Format: date */
            purchaseDate?: string | null;
            purchasePrice?: components["schemas"]["Decimal"];
        };
        Car: components["schemas"]["CarInput"] & {
            id: components["schemas"]["UUID"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CarPage: {
            items: components["schemas"]["Car"][];
            nextCursor: string | null;
        };
        ExpenseBase: {
            id: components["schemas"]["UUID"];
            carId: components["schemas"]["UUID"];
            /** Format: date-time */
            date: string;
            amount: components["schemas"]["Decimal"];
        };
        RefuelInput: {
            carId: components["schemas"]["UUID"];
            /** Format: date-time */
            date: string;
            station: string;
            odometerReading?: number | null;
            /** @enum {string} */
            fuel: "normal" | "special" | "other";
            liters: components["schemas"]["Decimal"];
            amount: components["schemas"]["Decimal"];
        };
        RefuelUpdate: {
            /** Format: date-time */
            date?: string;
            station?: string;
            odometerReading?: number | null;
            /** @enum {string} */
            fuel?: "normal" | "special" | "other";
            liters?: components["schemas"]["Decimal"];
            amount?: components["schemas"]["Decimal"];
        };
        Refuel: components["schemas"]["ExpenseBase"] & components["schemas"]["RefuelInput"] & {
            perLiter: components["schemas"]["Decimal"];
            distance?: number | null;
            consumption?: string | null;
        };
        RepairInput: {
            carId: components["schemas"]["UUID"];
            /** Format: date-time */
            date: string;
            station: string;
            odometerReading?: number | null;
            /** @enum {string} */
            type: "check" | "service" | "wearing_part" | "crash_repair";
            amount: components["schemas"]["Decimal"];
            description?: string;
        };
        RepairUpdate: {
            /** Format: date-time */
            date?: string;
            station?: string;
            odometerReading?: number | null;
            /** @enum {string} */
            type?: "check" | "service" | "wearing_part" | "crash_repair";
            amount?: components["schemas"]["Decimal"];
            description?: string;
        };
        Repair: components["schemas"]["ExpenseBase"] & components["schemas"]["RepairInput"];
        TicketInput: {
            carId: components["schemas"]["UUID"];
            /** Format: date-time */
            date: string;
            /** @enum {string} */
            type: "parking" | "velocity" | "other";
            location: string;
            amount: components["schemas"]["Decimal"];
            description?: string;
        };
        TicketUpdate: {
            /** Format: date-time */
            date?: string;
            /** @enum {string} */
            type?: "parking" | "velocity" | "other";
            location?: string;
            amount?: components["schemas"]["Decimal"];
            description?: string;
        };
        Ticket: components["schemas"]["ExpenseBase"] & components["schemas"]["TicketInput"];
        RefuelChart: {
            items: components["schemas"]["Refuel"][];
        };
        ExpenseStatistics: {
            items: {
                /** Format: date */
                date: string;
                refuels: components["schemas"]["Decimal"];
                repairs: components["schemas"]["Decimal"];
                tickets: components["schemas"]["Decimal"];
            }[];
        };
    };
    responses: {
        /** @description Redirect to the identity provider. */
        Redirect: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Session established and redirect to an allowed frontend path. */
        SessionRedirect: {
            headers: {
                /** @description HttpOnly Secure SameSite session cookie. */
                "Set-Cookie"?: string;
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication required or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource absent or not owned by caller. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request conflicts with existing state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error. */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Opaque cursor from nextCursor. */
        Cursor: string;
        Limit: number;
        CarId: components["schemas"]["UUID"];
        RefuelId: components["schemas"]["UUID"];
        RepairId: components["schemas"]["UUID"];
        TicketId: components["schemas"]["UUID"];
        CarFilter: components["schemas"]["UUID"];
        From: string;
        To: string;
        FromRequired: string;
        ToRequired: string;
        ReturnTo: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: {
        CarExpenseCollection: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            get: operations["listCarExpenses"];
            put?: never;
            post?: never;
            delete?: never;
            options?: never;
            head?: never;
            patch?: never;
            trace?: never;
        };
        ExpenseCollection: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            get: operations["listExpenses"];
            put?: never;
            post?: never;
            delete?: never;
            options?: never;
            head?: never;
            patch?: never;
            trace?: never;
        };
        RefuelCreate: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            get?: never;
            put?: never;
            post: operations["createRefuel"];
            delete?: never;
            options?: never;
            head?: never;
            patch?: never;
            trace?: never;
        };
        RepairCreate: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            get?: never;
            put?: never;
            post: operations["createRepair"];
            delete?: never;
            options?: never;
            head?: never;
            patch?: never;
            trace?: never;
        };
        TicketCreate: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            get?: never;
            put?: never;
            post: operations["createTicket"];
            delete?: never;
            options?: never;
            head?: never;
            patch?: never;
            trace?: never;
        };
        RefuelDetail: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            get: operations["getRefuel"];
            put?: never;
            post?: never;
            delete: operations["deleteRefuel"];
            options?: never;
            head?: never;
            patch: operations["updateRefuel"];
            trace?: never;
        };
        RepairDetail: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            get: operations["getRepair"];
            put?: never;
            post?: never;
            delete: operations["deleteRepair"];
            options?: never;
            head?: never;
            patch: operations["updateRepair"];
            trace?: never;
        };
        TicketDetail: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            get: operations["getTicket"];
            put?: never;
            post?: never;
            delete: operations["deleteTicket"];
            options?: never;
            head?: never;
            patch: operations["updateTicket"];
            trace?: never;
        };
        StationSuggestions: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            get: operations["listRefuelStations"];
            put?: never;
            post?: never;
            delete?: never;
            options?: never;
            head?: never;
            patch?: never;
            trace?: never;
        };
        LocationSuggestions: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            get: operations["listTicketLocations"];
            put?: never;
            post?: never;
            delete?: never;
            options?: never;
            head?: never;
            patch?: never;
            trace?: never;
        };
    };
}
export type $defs = Record<string, never>;
export interface operations {
    getAuthenticationMethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Passwordless authentication methods enabled for this deployment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationMethods"];
                };
            };
            default: components["responses"]["ServerError"];
        };
    };
    startOidcLogin: {
        parameters: {
            query?: {
                returnTo?: components["parameters"]["ReturnTo"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            302: components["responses"]["Redirect"];
            400: components["responses"]["BadRequest"];
        };
    };
    completeOidcLogin: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            302: components["responses"]["SessionRedirect"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    requestMagicLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkRequest"];
            };
        };
        responses: {
            /** @description Request accepted without revealing account existence. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    consumeMagicLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            302: components["responses"]["SessionRedirect"];
            400: components["responses"]["BadRequest"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session invalidated and cookie cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Updated profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            default: components["responses"]["ServerError"];
        };
    };
    listCars: {
        parameters: {
            query?: {
                /** @description Opaque cursor from nextCursor. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cars ordered by creation time then ID. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    createCar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarInput"];
            };
        };
        responses: {
            /** @description Created car. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Car"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    getCar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carId: components["parameters"]["CarId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Car. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Car"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    deleteCar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carId: components["parameters"]["CarId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Car and associated expenses deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    updateCar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carId: components["parameters"]["CarId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarUpdate"];
            };
        };
        responses: {
            /** @description Updated car. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Car"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    getRefuelChart: {
        parameters: {
            query?: {
                carId?: components["parameters"]["CarFilter"];
                from?: components["parameters"]["From"];
                to?: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Complete chart series ordered by date then ID. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefuelChart"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    getExpenseStatistics: {
        parameters: {
            query: {
                from: components["parameters"]["FromRequired"];
                to: components["parameters"]["ToRequired"];
                carId?: components["parameters"]["CarFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categorized daily expense totals. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseStatistics"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    listCarExpenses: {
        parameters: {
            query?: {
                /** @description Opaque cursor from nextCursor. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                from?: components["parameters"]["From"];
                to?: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated car expense records. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    listExpenses: {
        parameters: {
            query?: {
                /** @description Opaque cursor from nextCursor. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                carId?: components["parameters"]["CarFilter"];
                from?: components["parameters"]["From"];
                to?: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated records ordered by date then ID. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    createRefuel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefuelInput"];
            };
        };
        responses: {
            /** @description Created refuel. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refuel"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    createRepair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepairInput"];
            };
        };
        responses: {
            /** @description Created repair. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repair"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    createTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketInput"];
            };
        };
        responses: {
            /** @description Created ticket. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    getRefuel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refuel. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refuel"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    deleteRefuel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    updateRefuel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefuelUpdate"];
            };
        };
        responses: {
            /** @description Updated refuel. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refuel"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    getRepair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repair. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repair"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    deleteRepair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    updateRepair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepairUpdate"];
            };
        };
        responses: {
            /** @description Updated repair. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repair"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    getTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticket. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    deleteTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    updateTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketUpdate"];
            };
        };
        responses: {
            /** @description Updated ticket. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    listRefuelStations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Distinct caller-owned station names. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    listTicketLocations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Distinct caller-owned locations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
}
