/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuthenticationMethods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oidc/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["startOidcLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oidc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["completeOidcLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestMagicLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic-links/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["consumeMagicLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Starts a discoverable-credential passkey login. No email is accepted or revealed. The returned options contain no allowed-credential list and require user verification. A short-lived HttpOnly ceremony cookie correlates the options with the following assertion. */
        post: operations["startPasskeyLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Verifies a passkey assertion for the ceremony started by `startPasskeyLogin` and establishes a session for the account that owns the credential. Never creates an account. */
        post: operations["completePasskeyLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete: operations["logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/passkeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPasskeys"];
        put?: never;
        /** @description Completes the registration ceremony started by `startPasskeyRegistration`. Requires a session established at most 5 minutes ago. */
        post: operations["registerPasskey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/passkeys/registration-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Starts registering a discoverable passkey for the caller. Requires a session established at most 5 minutes ago. The caller's existing passkeys are excluded. A short-lived HttpOnly ceremony cookie correlates the options with the following registration. */
        post: operations["startPasskeyRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/passkeys/{passkeyId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                passkeyId: components["parameters"]["PasskeyId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Deletes the passkey and revokes every session established with it, including the caller's session if it was. In that case the session cookie is cleared. No fresh login is required. */
        delete: operations["deletePasskey"];
        options?: never;
        head?: never;
        patch: operations["renamePasskey"];
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Updates the caller's first and/or last name. Names are trimmed and may be empty. The email address is read-only; a body containing `email` is rejected with `400` and a `read_only` reason for `email`, and nothing is applied. */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/cars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCars"];
        put?: never;
        post: operations["createCar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cars/{carId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carId: components["parameters"]["CarId"];
            };
            cookie?: never;
        };
        get: operations["getCar"];
        put?: never;
        post?: never;
        delete: operations["deleteCar"];
        options?: never;
        head?: never;
        patch: operations["updateCar"];
        trace?: never;
    };
    "/refuels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRefuels"];
        put?: never;
        post: components["pathItems"]["RefuelCreate"]["post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refuels/{refuelId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                refuelId: components["parameters"]["RefuelId"];
            };
            cookie?: never;
        };
        get: components["pathItems"]["RefuelDetail"]["get"];
        put?: never;
        post?: never;
        delete: components["pathItems"]["RefuelDetail"]["delete"];
        options?: never;
        head?: never;
        patch: components["pathItems"]["RefuelDetail"]["patch"];
        trace?: never;
    };
    "/refuels/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRefuelStations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refuels/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRefuelChart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repairs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRepairs"];
        put?: never;
        post: components["pathItems"]["RepairCreate"]["post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repairs/{repairId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repairId: components["parameters"]["RepairId"];
            };
            cookie?: never;
        };
        get: components["pathItems"]["RepairDetail"]["get"];
        put?: never;
        post?: never;
        delete: components["pathItems"]["RepairDetail"]["delete"];
        options?: never;
        head?: never;
        patch: components["pathItems"]["RepairDetail"]["patch"];
        trace?: never;
    };
    "/repairs/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRepairStations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTickets"];
        put?: never;
        post: components["pathItems"]["TicketCreate"]["post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        get: components["pathItems"]["TicketDetail"]["get"];
        put?: never;
        post?: never;
        delete: components["pathItems"]["TicketDetail"]["delete"];
        options?: never;
        head?: never;
        patch: components["pathItems"]["TicketDetail"]["patch"];
        trace?: never;
    };
    "/tickets/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTicketLocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExpenseStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        UUID: string;
        Decimal: string;
        NullableDecimal: string | null;
        Error: {
            /** @example validation_failed */
            code: string;
            message: string;
            /** @description Validation details keyed by request member name (`_body` for the request as a whole). Values are machine-readable reasons, such as `read_only` (the member cannot be changed), `unknown` (the member is not part of the request schema), `invalid_type` (wrong JSON type), `too_long` (exceeds the documented maximum length), `required` (a required member is missing), `empty` (a string is blank after trimming), `invalid_enum` (not one of the documented codes), `invalid_date` (not an RFC 3339 full-date), `invalid_decimal` (not a decimal string), and `negative` (a numeric value below zero). */
            fields?: {
                [key: string]: string;
            };
        };
        Profile: {
            id: components["schemas"]["UUID"];
            /** Format: email */
            email: string;
            firstName: string;
            lastName: string;
        };
        ProfileUpdate: {
            firstName?: string;
            lastName?: string;
        };
        Session: {
            profile: components["schemas"]["Profile"];
        };
        AuthenticationMethods: {
            methods: ("magic_link" | "oidc" | "passkey")[];
        };
        PasskeySummary: {
            id: components["schemas"]["UUID"];
            name: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastUsedAt: string | null;
            /** @description Authenticator model name derived from its AAGUID, or `null` when unknown. */
            authenticatorName: string | null;
            /** @description Whether the passkey is synced (backed up) across devices. */
            backedUp: boolean;
        };
        PasskeyList: {
            items: components["schemas"]["PasskeySummary"][];
        };
        /** @description Trimmed before validation; must not be blank. */
        PasskeyName: string;
        PasskeyRegistration: {
            name: components["schemas"]["PasskeyName"];
            credential: components["schemas"]["PublicKeyCredentialJSON"];
        };
        PasskeyUpdate: {
            name: components["schemas"]["PasskeyName"];
        };
        PasskeyCreationOptions: {
            /** @description W3C WebAuthn `PublicKeyCredentialCreationOptionsJSON` (binary members base64url-encoded). */
            publicKey: {
                [key: string]: unknown;
            };
        };
        PasskeyRequestOptions: {
            /** @description W3C WebAuthn `PublicKeyCredentialRequestOptionsJSON` (binary members base64url-encoded). */
            publicKey: {
                [key: string]: unknown;
            };
        };
        /** @description W3C WebAuthn `RegistrationResponseJSON` or `AuthenticationResponseJSON` (binary members base64url-encoded). */
        PublicKeyCredentialJSON: {
            id: string;
            rawId: string;
            /** @enum {string} */
            type: "public-key";
            response: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        MagicLinkRequest: {
            /** Format: email */
            email: string;
            /** Format: uri-reference */
            returnTo?: string;
        };
        CarInput: {
            type: string;
            make: string;
            name: string;
            /** @enum {string} */
            fuel: "other" | "diesel" | "gasoline" | "electric";
            /** Format: date */
            firstRegistration?: string | null;
            licensePlate?: string | null;
            fin?: string | null;
            /** @default true */
            isActive: boolean;
            /** Format: date */
            purchaseDate?: string | null;
            purchasePrice?: components["schemas"]["NullableDecimal"];
        };
        CarUpdate: {
            type?: string;
            make?: string;
            name?: string;
            /** @enum {string} */
            fuel?: "other" | "diesel" | "gasoline" | "electric";
            /** Format: date */
            firstRegistration?: string | null;
            licensePlate?: string | null;
            fin?: string | null;
            isActive?: boolean;
            /** Format: date */
            purchaseDate?: string | null;
            purchasePrice?: components["schemas"]["NullableDecimal"];
        };
        /** @description A car. Every member is always present; `firstRegistration`, `licensePlate`, `fin`, `purchaseDate`, and `purchasePrice` are `null` when not recorded. */
        Car: {
            id: components["schemas"]["UUID"];
            type: string;
            make: string;
            name: string;
            /** @enum {string} */
            fuel: "other" | "diesel" | "gasoline" | "electric";
            /** Format: date */
            firstRegistration: string | null;
            licensePlate: string | null;
            fin: string | null;
            isActive: boolean;
            /** Format: date */
            purchaseDate: string | null;
            purchasePrice: components["schemas"]["NullableDecimal"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CarPage: {
            items: components["schemas"]["Car"][];
            nextCursor: string | null;
        };
        RefuelInput: {
            carId: components["schemas"]["UUID"];
            /** Format: date-time */
            date: string;
            station: string;
            odometerReading?: number | null;
            /** @enum {string} */
            fuel: "normal" | "special" | "other";
            liters: components["schemas"]["Decimal"];
            amount: components["schemas"]["Decimal"];
        };
        RefuelUpdate: {
            /** Format: date-time */
            date?: string;
            station?: string;
            odometerReading?: number | null;
            /** @enum {string} */
            fuel?: "normal" | "special" | "other";
            liters?: components["schemas"]["Decimal"];
            amount?: components["schemas"]["Decimal"];
        };
        Refuel: {
            id: components["schemas"]["UUID"];
            carId: components["schemas"]["UUID"];
            /** Format: date-time */
            date: string;
            station: string;
            odometerReading: number | null;
            /** @enum {string} */
            fuel: "normal" | "special" | "other";
            liters: components["schemas"]["Decimal"];
            amount: components["schemas"]["Decimal"];
            perLiter: components["schemas"]["Decimal"];
            distance: number | null;
            consumption: string | null;
        };
        RefuelPage: {
            items: components["schemas"]["Refuel"][];
            nextCursor: string | null;
        };
        RepairInput: {
            carId: components["schemas"]["UUID"];
            /** Format: date-time */
            date: string;
            station: string;
            odometerReading?: number | null;
            /** @enum {string} */
            type: "check" | "service" | "wearing_part" | "crash_repair";
            amount: components["schemas"]["Decimal"];
            description?: string;
        };
        RepairUpdate: {
            /** Format: date-time */
            date?: string;
            station?: string;
            odometerReading?: number | null;
            /** @enum {string} */
            type?: "check" | "service" | "wearing_part" | "crash_repair";
            amount?: components["schemas"]["Decimal"];
            description?: string;
        };
        /** @description A repair. Every member is always present; `odometerReading` is `null` and `description` is empty when not recorded. */
        Repair: {
            id: components["schemas"]["UUID"];
            carId: components["schemas"]["UUID"];
            /** Format: date-time */
            date: string;
            station: string;
            odometerReading: number | null;
            /** @enum {string} */
            type: "check" | "service" | "wearing_part" | "crash_repair";
            amount: components["schemas"]["Decimal"];
            description: string;
        };
        RepairPage: {
            items: components["schemas"]["Repair"][];
            nextCursor: string | null;
        };
        TicketInput: {
            carId: components["schemas"]["UUID"];
            /** Format: date-time */
            date: string;
            /** @enum {string} */
            type: "parking" | "velocity" | "other";
            location: string;
            amount: components["schemas"]["Decimal"];
            description?: string;
        };
        TicketUpdate: {
            /** Format: date-time */
            date?: string;
            /** @enum {string} */
            type?: "parking" | "velocity" | "other";
            location?: string;
            amount?: components["schemas"]["Decimal"];
            description?: string;
        };
        /** @description A ticket. Every member is always present; `description` is empty when not recorded. */
        Ticket: {
            id: components["schemas"]["UUID"];
            carId: components["schemas"]["UUID"];
            /** Format: date-time */
            date: string;
            /** @enum {string} */
            type: "parking" | "velocity" | "other";
            location: string;
            amount: components["schemas"]["Decimal"];
            description: string;
        };
        TicketPage: {
            items: components["schemas"]["Ticket"][];
            nextCursor: string | null;
        };
        RefuelChart: {
            items: components["schemas"]["Refuel"][];
        };
        ExpenseStatistics: {
            items: {
                /** Format: date-time */
                date: string;
                /** @enum {string} */
                kind: "refuel" | "repair" | "ticket";
                amount: components["schemas"]["Decimal"];
            }[];
        };
    };
    responses: {
        /** @description Redirect to the identity provider. */
        Redirect: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Session established and redirect to an allowed frontend path. */
        SessionRedirect: {
            headers: {
                /** @description HttpOnly Secure SameSite session cookie. */
                "Set-Cookie"?: string;
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication required or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource absent or not owned by caller. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request conflicts with existing state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The session is older than the fresh-login window (5 minutes); the error code is `reauthentication_required`. */
        ReauthenticationRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error. */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Opaque cursor from nextCursor. */
        Cursor: string;
        Limit: number;
        CarId: components["schemas"]["UUID"];
        PasskeyId: components["schemas"]["UUID"];
        RefuelId: components["schemas"]["UUID"];
        RepairId: components["schemas"]["UUID"];
        TicketId: components["schemas"]["UUID"];
        CarFilter: components["schemas"]["UUID"];
        From: string;
        To: string;
        /** @description Inclusive start of the range. */
        FromRequired: string;
        /** @description Exclusive end of the range. */
        ToRequired: string;
        ReturnTo: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: {
        RefuelCreate: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            get?: never;
            put?: never;
            post: operations["createRefuel"];
            delete?: never;
            options?: never;
            head?: never;
            patch?: never;
            trace?: never;
        };
        RepairCreate: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            get?: never;
            put?: never;
            post: operations["createRepair"];
            delete?: never;
            options?: never;
            head?: never;
            patch?: never;
            trace?: never;
        };
        TicketCreate: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            get?: never;
            put?: never;
            post: operations["createTicket"];
            delete?: never;
            options?: never;
            head?: never;
            patch?: never;
            trace?: never;
        };
        RefuelDetail: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            get: operations["getRefuel"];
            put?: never;
            post?: never;
            delete: operations["deleteRefuel"];
            options?: never;
            head?: never;
            patch: operations["updateRefuel"];
            trace?: never;
        };
        RepairDetail: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            get: operations["getRepair"];
            put?: never;
            post?: never;
            delete: operations["deleteRepair"];
            options?: never;
            head?: never;
            patch: operations["updateRepair"];
            trace?: never;
        };
        TicketDetail: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            get: operations["getTicket"];
            put?: never;
            post?: never;
            delete: operations["deleteTicket"];
            options?: never;
            head?: never;
            patch: operations["updateTicket"];
            trace?: never;
        };
    };
}
export type $defs = Record<string, never>;
export interface operations {
    getAuthenticationMethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Passwordless authentication methods enabled for this deployment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationMethods"];
                };
            };
            default: components["responses"]["ServerError"];
        };
    };
    startOidcLogin: {
        parameters: {
            query?: {
                returnTo?: components["parameters"]["ReturnTo"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            302: components["responses"]["Redirect"];
            400: components["responses"]["BadRequest"];
        };
    };
    completeOidcLogin: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            302: components["responses"]["SessionRedirect"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    requestMagicLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkRequest"];
            };
        };
        responses: {
            /** @description Request accepted without revealing account existence. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    consumeMagicLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            302: components["responses"]["SessionRedirect"];
            400: components["responses"]["BadRequest"];
        };
    };
    startPasskeyLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebAuthn request options in their JSON form. */
            200: {
                headers: {
                    /** @description HttpOnly Secure SameSite=Strict passkey ceremony cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyRequestOptions"];
                };
            };
            default: components["responses"]["ServerError"];
        };
    };
    completePasskeyLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicKeyCredentialJSON"];
            };
        };
        responses: {
            /** @description Session established. */
            204: {
                headers: {
                    /** @description HttpOnly Secure SameSite session cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session invalidated and cookie cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    listPasskeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's passkeys ordered by creation time then ID. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    registerPasskey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasskeyRegistration"];
            };
        };
        responses: {
            /** @description Registered passkey. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeySummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["ReauthenticationRequired"];
            409: components["responses"]["Conflict"];
            default: components["responses"]["ServerError"];
        };
    };
    startPasskeyRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebAuthn creation options in their JSON form. */
            200: {
                headers: {
                    /** @description HttpOnly Secure SameSite=Strict passkey ceremony cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyCreationOptions"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["ReauthenticationRequired"];
            default: components["responses"]["ServerError"];
        };
    };
    deletePasskey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                passkeyId: components["parameters"]["PasskeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Passkey deleted and its sessions revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    renamePasskey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                passkeyId: components["parameters"]["PasskeyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasskeyUpdate"];
            };
        };
        responses: {
            /** @description Renamed passkey. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeySummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Updated profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    listCars: {
        parameters: {
            query?: {
                /** @description Opaque cursor from nextCursor. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cars ordered by creation time then ID. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    createCar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarInput"];
            };
        };
        responses: {
            /** @description Created car. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Car"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    getCar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carId: components["parameters"]["CarId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Car. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Car"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    deleteCar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carId: components["parameters"]["CarId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Car and associated expenses deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    updateCar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carId: components["parameters"]["CarId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarUpdate"];
            };
        };
        responses: {
            /** @description Updated car. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Car"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    listRefuels: {
        parameters: {
            query?: {
                /** @description Opaque cursor from nextCursor. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                carId?: components["parameters"]["CarFilter"];
                from?: components["parameters"]["From"];
                to?: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's refuels ordered by date then ID. A `carId` that names no car of the caller's yields an empty page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefuelPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    listRefuelStations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Distinct station names from the caller's refuels, in ascending order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    getRefuelChart: {
        parameters: {
            query?: {
                carId?: components["parameters"]["CarFilter"];
                from?: components["parameters"]["From"];
                to?: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Complete chart series ordered by date then ID. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefuelChart"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    listRepairs: {
        parameters: {
            query?: {
                /** @description Opaque cursor from nextCursor. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                carId?: components["parameters"]["CarFilter"];
                from?: components["parameters"]["From"];
                to?: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's repairs ordered by date then ID. A `carId` that names no car of the caller's yields an empty page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepairPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    listRepairStations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Distinct station names from the caller's repairs, in ascending order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    listTickets: {
        parameters: {
            query?: {
                /** @description Opaque cursor from nextCursor. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                carId?: components["parameters"]["CarFilter"];
                from?: components["parameters"]["From"];
                to?: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's tickets ordered by date then ID. A `carId` that names no car of the caller's yields an empty page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    listTicketLocations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Distinct locations from the caller's tickets, in ascending order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    getExpenseStatistics: {
        parameters: {
            query: {
                /** @description Inclusive start of the range. */
                from: components["parameters"]["FromRequired"];
                /** @description Exclusive end of the range. */
                to: components["parameters"]["ToRequired"];
                carId?: components["parameters"]["CarFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's refuels, repairs and tickets dated on or after `from` and before `to`, ordered by date, unpaged. They are not grouped into days or months, because only the client knows the viewer's time zone. A `carId` that names no car of the caller's yields no rows. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseStatistics"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["ServerError"];
        };
    };
    createRefuel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefuelInput"];
            };
        };
        responses: {
            /** @description Created refuel. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refuel"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    createRepair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepairInput"];
            };
        };
        responses: {
            /** @description Created repair. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repair"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    createTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketInput"];
            };
        };
        responses: {
            /** @description Created ticket. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    getRefuel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refuel. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refuel"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    deleteRefuel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    updateRefuel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefuelUpdate"];
            };
        };
        responses: {
            /** @description Updated refuel. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refuel"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    getRepair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repair. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repair"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    deleteRepair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    updateRepair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepairUpdate"];
            };
        };
        responses: {
            /** @description Updated repair. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repair"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    getTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticket. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    deleteTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
    updateTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketUpdate"];
            };
        };
        responses: {
            /** @description Updated ticket. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["ServerError"];
        };
    };
}
