/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated.home'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedRefuelsRouteImport } from './routes/_authenticated.refuels'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated.tickets'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthenticatedCarsIndexRouteImport } from './routes/_authenticated.cars.index'
import { Route as AuthenticatedCarsCreateRouteImport } from './routes/_authenticated.cars.create'
import { Route as AuthenticatedRepairsIndexRouteImport } from './routes/_authenticated.repairs.index'
import { Route as AuthenticatedRepairsCreateRouteImport } from './routes/_authenticated.repairs.create'
import { Route as AuthenticatedCarsCarIdIndexRouteImport } from './routes/_authenticated.cars.$carId.index'
import { Route as AuthenticatedCarsCarIdEditRouteImport } from './routes/_authenticated.cars.$carId.edit'
import { Route as AuthenticatedRepairsRepairIdEditRouteImport } from './routes/_authenticated.repairs.$repairId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRefuelsRoute = AuthenticatedRefuelsRouteImport.update({
  id: '/refuels',
  path: '/refuels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCarsIndexRoute = AuthenticatedCarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCarsCreateRoute = AuthenticatedCarsCreateRouteImport.update({
  id: '/cars/create',
  path: '/cars/create',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRepairsIndexRoute =
  AuthenticatedRepairsIndexRouteImport.update({
    id: '/repairs/',
    path: '/repairs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRepairsCreateRoute =
  AuthenticatedRepairsCreateRouteImport.update({
    id: '/repairs/create',
    path: '/repairs/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCarsCarIdIndexRoute =
  AuthenticatedCarsCarIdIndexRouteImport.update({
    id: '/cars/$carId/',
    path: '/cars/$carId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCarsCarIdEditRoute =
  AuthenticatedCarsCarIdEditRouteImport.update({
    id: '/cars/$carId/edit',
    path: '/cars/$carId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRepairsRepairIdEditRoute =
  AuthenticatedRepairsRepairIdEditRouteImport.update({
    id: '/repairs/$repairId/edit',
    path: '/repairs/$repairId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/refuels': typeof AuthenticatedRefuelsRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/auth/login': typeof AuthLoginRoute
  '/cars/create': typeof AuthenticatedCarsCreateRoute
  '/repairs/create': typeof AuthenticatedRepairsCreateRoute
  '/cars/': typeof AuthenticatedCarsIndexRoute
  '/repairs/': typeof AuthenticatedRepairsIndexRoute
  '/cars/$carId/edit': typeof AuthenticatedCarsCarIdEditRoute
  '/repairs/$repairId/edit': typeof AuthenticatedRepairsRepairIdEditRoute
  '/cars/$carId/': typeof AuthenticatedCarsCarIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/refuels': typeof AuthenticatedRefuelsRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/auth/login': typeof AuthLoginRoute
  '/cars/create': typeof AuthenticatedCarsCreateRoute
  '/repairs/create': typeof AuthenticatedRepairsCreateRoute
  '/cars': typeof AuthenticatedCarsIndexRoute
  '/repairs': typeof AuthenticatedRepairsIndexRoute
  '/cars/$carId/edit': typeof AuthenticatedCarsCarIdEditRoute
  '/repairs/$repairId/edit': typeof AuthenticatedRepairsRepairIdEditRoute
  '/cars/$carId': typeof AuthenticatedCarsCarIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/refuels': typeof AuthenticatedRefuelsRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/auth/login': typeof AuthLoginRoute
  '/_authenticated/cars/create': typeof AuthenticatedCarsCreateRoute
  '/_authenticated/repairs/create': typeof AuthenticatedRepairsCreateRoute
  '/_authenticated/cars/': typeof AuthenticatedCarsIndexRoute
  '/_authenticated/repairs/': typeof AuthenticatedRepairsIndexRoute
  '/_authenticated/cars/$carId/edit': typeof AuthenticatedCarsCarIdEditRoute
  '/_authenticated/repairs/$repairId/edit': typeof AuthenticatedRepairsRepairIdEditRoute
  '/_authenticated/cars/$carId/': typeof AuthenticatedCarsCarIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/profile'
    | '/refuels'
    | '/tickets'
    | '/auth/login'
    | '/cars/create'
    | '/repairs/create'
    | '/cars/'
    | '/repairs/'
    | '/cars/$carId/edit'
    | '/repairs/$repairId/edit'
    | '/cars/$carId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/profile'
    | '/refuels'
    | '/tickets'
    | '/auth/login'
    | '/cars/create'
    | '/repairs/create'
    | '/cars'
    | '/repairs'
    | '/cars/$carId/edit'
    | '/repairs/$repairId/edit'
    | '/cars/$carId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/refuels'
    | '/_authenticated/tickets'
    | '/auth/login'
    | '/_authenticated/cars/create'
    | '/_authenticated/repairs/create'
    | '/_authenticated/cars/'
    | '/_authenticated/repairs/'
    | '/_authenticated/cars/$carId/edit'
    | '/_authenticated/repairs/$repairId/edit'
    | '/_authenticated/cars/$carId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/refuels': {
      id: '/_authenticated/refuels'
      path: '/refuels'
      fullPath: '/refuels'
      preLoaderRoute: typeof AuthenticatedRefuelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cars/': {
      id: '/_authenticated/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof AuthenticatedCarsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cars/create': {
      id: '/_authenticated/cars/create'
      path: '/cars/create'
      fullPath: '/cars/create'
      preLoaderRoute: typeof AuthenticatedCarsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repairs/': {
      id: '/_authenticated/repairs/'
      path: '/repairs'
      fullPath: '/repairs/'
      preLoaderRoute: typeof AuthenticatedRepairsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repairs/create': {
      id: '/_authenticated/repairs/create'
      path: '/repairs/create'
      fullPath: '/repairs/create'
      preLoaderRoute: typeof AuthenticatedRepairsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cars/$carId/': {
      id: '/_authenticated/cars/$carId/'
      path: '/cars/$carId'
      fullPath: '/cars/$carId/'
      preLoaderRoute: typeof AuthenticatedCarsCarIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cars/$carId/edit': {
      id: '/_authenticated/cars/$carId/edit'
      path: '/cars/$carId/edit'
      fullPath: '/cars/$carId/edit'
      preLoaderRoute: typeof AuthenticatedCarsCarIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repairs/$repairId/edit': {
      id: '/_authenticated/repairs/$repairId/edit'
      path: '/repairs/$repairId/edit'
      fullPath: '/repairs/$repairId/edit'
      preLoaderRoute: typeof AuthenticatedRepairsRepairIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRefuelsRoute: typeof AuthenticatedRefuelsRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedCarsCreateRoute: typeof AuthenticatedCarsCreateRoute
  AuthenticatedRepairsCreateRoute: typeof AuthenticatedRepairsCreateRoute
  AuthenticatedCarsIndexRoute: typeof AuthenticatedCarsIndexRoute
  AuthenticatedRepairsIndexRoute: typeof AuthenticatedRepairsIndexRoute
  AuthenticatedCarsCarIdEditRoute: typeof AuthenticatedCarsCarIdEditRoute
  AuthenticatedRepairsRepairIdEditRoute: typeof AuthenticatedRepairsRepairIdEditRoute
  AuthenticatedCarsCarIdIndexRoute: typeof AuthenticatedCarsCarIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRefuelsRoute: AuthenticatedRefuelsRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedCarsCreateRoute: AuthenticatedCarsCreateRoute,
  AuthenticatedRepairsCreateRoute: AuthenticatedRepairsCreateRoute,
  AuthenticatedCarsIndexRoute: AuthenticatedCarsIndexRoute,
  AuthenticatedRepairsIndexRoute: AuthenticatedRepairsIndexRoute,
  AuthenticatedCarsCarIdEditRoute: AuthenticatedCarsCarIdEditRoute,
  AuthenticatedRepairsRepairIdEditRoute: AuthenticatedRepairsRepairIdEditRoute,
  AuthenticatedCarsCarIdIndexRoute: AuthenticatedCarsCarIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
