/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthenticatedCarsIndexRouteImport } from './routes/_authenticated/cars/index'
import { Route as AuthenticatedCarsCreateRouteImport } from './routes/_authenticated/cars/create'
import { Route as AuthenticatedRefuelsIndexRouteImport } from './routes/_authenticated/refuels/index'
import { Route as AuthenticatedRefuelsCreateRouteImport } from './routes/_authenticated/refuels/create'
import { Route as AuthenticatedRepairsIndexRouteImport } from './routes/_authenticated/repairs/index'
import { Route as AuthenticatedRepairsCreateRouteImport } from './routes/_authenticated/repairs/create'
import { Route as AuthenticatedCarsCarIdIndexRouteImport } from './routes/_authenticated/cars/$carId/index'
import { Route as AuthenticatedCarsCarIdEditRouteImport } from './routes/_authenticated/cars/$carId/edit'
import { Route as AuthenticatedRefuelsRefuelIdEditRouteImport } from './routes/_authenticated/refuels/$refuelId/edit'
import { Route as AuthenticatedRepairsRepairIdEditRouteImport } from './routes/_authenticated/repairs/$repairId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCarsIndexRoute = AuthenticatedCarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarsCreateRoute = AuthenticatedCarsCreateRouteImport.update({
  id: '/cars/create',
  path: '/cars/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRefuelsIndexRoute =
  AuthenticatedRefuelsIndexRouteImport.update({
    id: '/refuels/',
    path: '/refuels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRefuelsCreateRoute =
  AuthenticatedRefuelsCreateRouteImport.update({
    id: '/refuels/create',
    path: '/refuels/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRepairsIndexRoute =
  AuthenticatedRepairsIndexRouteImport.update({
    id: '/repairs/',
    path: '/repairs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRepairsCreateRoute =
  AuthenticatedRepairsCreateRouteImport.update({
    id: '/repairs/create',
    path: '/repairs/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarsCarIdIndexRoute =
  AuthenticatedCarsCarIdIndexRouteImport.update({
    id: '/cars/$carId/',
    path: '/cars/$carId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarsCarIdEditRoute =
  AuthenticatedCarsCarIdEditRouteImport.update({
    id: '/cars/$carId/edit',
    path: '/cars/$carId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRefuelsRefuelIdEditRoute =
  AuthenticatedRefuelsRefuelIdEditRouteImport.update({
    id: '/refuels/$refuelId/edit',
    path: '/refuels/$refuelId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRepairsRepairIdEditRoute =
  AuthenticatedRepairsRepairIdEditRouteImport.update({
    id: '/repairs/$repairId/edit',
    path: '/repairs/$repairId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/auth/login': typeof AuthLoginRoute
  '/cars/create': typeof AuthenticatedCarsCreateRoute
  '/refuels/create': typeof AuthenticatedRefuelsCreateRoute
  '/repairs/create': typeof AuthenticatedRepairsCreateRoute
  '/cars/': typeof AuthenticatedCarsIndexRoute
  '/refuels/': typeof AuthenticatedRefuelsIndexRoute
  '/repairs/': typeof AuthenticatedRepairsIndexRoute
  '/cars/$carId/edit': typeof AuthenticatedCarsCarIdEditRoute
  '/refuels/$refuelId/edit': typeof AuthenticatedRefuelsRefuelIdEditRoute
  '/repairs/$repairId/edit': typeof AuthenticatedRepairsRepairIdEditRoute
  '/cars/$carId/': typeof AuthenticatedCarsCarIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/auth/login': typeof AuthLoginRoute
  '/cars/create': typeof AuthenticatedCarsCreateRoute
  '/refuels/create': typeof AuthenticatedRefuelsCreateRoute
  '/repairs/create': typeof AuthenticatedRepairsCreateRoute
  '/cars': typeof AuthenticatedCarsIndexRoute
  '/refuels': typeof AuthenticatedRefuelsIndexRoute
  '/repairs': typeof AuthenticatedRepairsIndexRoute
  '/cars/$carId/edit': typeof AuthenticatedCarsCarIdEditRoute
  '/refuels/$refuelId/edit': typeof AuthenticatedRefuelsRefuelIdEditRoute
  '/repairs/$repairId/edit': typeof AuthenticatedRepairsRepairIdEditRoute
  '/cars/$carId': typeof AuthenticatedCarsCarIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/auth/login': typeof AuthLoginRoute
  '/_authenticated/cars/create': typeof AuthenticatedCarsCreateRoute
  '/_authenticated/refuels/create': typeof AuthenticatedRefuelsCreateRoute
  '/_authenticated/repairs/create': typeof AuthenticatedRepairsCreateRoute
  '/_authenticated/cars/': typeof AuthenticatedCarsIndexRoute
  '/_authenticated/refuels/': typeof AuthenticatedRefuelsIndexRoute
  '/_authenticated/repairs/': typeof AuthenticatedRepairsIndexRoute
  '/_authenticated/cars/$carId/edit': typeof AuthenticatedCarsCarIdEditRoute
  '/_authenticated/refuels/$refuelId/edit': typeof AuthenticatedRefuelsRefuelIdEditRoute
  '/_authenticated/repairs/$repairId/edit': typeof AuthenticatedRepairsRepairIdEditRoute
  '/_authenticated/cars/$carId/': typeof AuthenticatedCarsCarIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/profile'
    | '/tickets'
    | '/auth/login'
    | '/cars/create'
    | '/refuels/create'
    | '/repairs/create'
    | '/cars/'
    | '/refuels/'
    | '/repairs/'
    | '/cars/$carId/edit'
    | '/refuels/$refuelId/edit'
    | '/repairs/$repairId/edit'
    | '/cars/$carId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/profile'
    | '/tickets'
    | '/auth/login'
    | '/cars/create'
    | '/refuels/create'
    | '/repairs/create'
    | '/cars'
    | '/refuels'
    | '/repairs'
    | '/cars/$carId/edit'
    | '/refuels/$refuelId/edit'
    | '/repairs/$repairId/edit'
    | '/cars/$carId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/tickets'
    | '/auth/login'
    | '/_authenticated/cars/create'
    | '/_authenticated/refuels/create'
    | '/_authenticated/repairs/create'
    | '/_authenticated/cars/'
    | '/_authenticated/refuels/'
    | '/_authenticated/repairs/'
    | '/_authenticated/cars/$carId/edit'
    | '/_authenticated/refuels/$refuelId/edit'
    | '/_authenticated/repairs/$repairId/edit'
    | '/_authenticated/cars/$carId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cars/': {
      id: '/_authenticated/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof AuthenticatedCarsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cars/create': {
      id: '/_authenticated/cars/create'
      path: '/cars/create'
      fullPath: '/cars/create'
      preLoaderRoute: typeof AuthenticatedCarsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/refuels/': {
      id: '/_authenticated/refuels/'
      path: '/refuels'
      fullPath: '/refuels/'
      preLoaderRoute: typeof AuthenticatedRefuelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/refuels/create': {
      id: '/_authenticated/refuels/create'
      path: '/refuels/create'
      fullPath: '/refuels/create'
      preLoaderRoute: typeof AuthenticatedRefuelsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repairs/': {
      id: '/_authenticated/repairs/'
      path: '/repairs'
      fullPath: '/repairs/'
      preLoaderRoute: typeof AuthenticatedRepairsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repairs/create': {
      id: '/_authenticated/repairs/create'
      path: '/repairs/create'
      fullPath: '/repairs/create'
      preLoaderRoute: typeof AuthenticatedRepairsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cars/$carId/': {
      id: '/_authenticated/cars/$carId/'
      path: '/cars/$carId'
      fullPath: '/cars/$carId/'
      preLoaderRoute: typeof AuthenticatedCarsCarIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cars/$carId/edit': {
      id: '/_authenticated/cars/$carId/edit'
      path: '/cars/$carId/edit'
      fullPath: '/cars/$carId/edit'
      preLoaderRoute: typeof AuthenticatedCarsCarIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/refuels/$refuelId/edit': {
      id: '/_authenticated/refuels/$refuelId/edit'
      path: '/refuels/$refuelId/edit'
      fullPath: '/refuels/$refuelId/edit'
      preLoaderRoute: typeof AuthenticatedRefuelsRefuelIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repairs/$repairId/edit': {
      id: '/_authenticated/repairs/$repairId/edit'
      path: '/repairs/$repairId/edit'
      fullPath: '/repairs/$repairId/edit'
      preLoaderRoute: typeof AuthenticatedRepairsRepairIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedCarsCreateRoute: typeof AuthenticatedCarsCreateRoute
  AuthenticatedRefuelsCreateRoute: typeof AuthenticatedRefuelsCreateRoute
  AuthenticatedRepairsCreateRoute: typeof AuthenticatedRepairsCreateRoute
  AuthenticatedCarsIndexRoute: typeof AuthenticatedCarsIndexRoute
  AuthenticatedRefuelsIndexRoute: typeof AuthenticatedRefuelsIndexRoute
  AuthenticatedRepairsIndexRoute: typeof AuthenticatedRepairsIndexRoute
  AuthenticatedCarsCarIdEditRoute: typeof AuthenticatedCarsCarIdEditRoute
  AuthenticatedRefuelsRefuelIdEditRoute: typeof AuthenticatedRefuelsRefuelIdEditRoute
  AuthenticatedRepairsRepairIdEditRoute: typeof AuthenticatedRepairsRepairIdEditRoute
  AuthenticatedCarsCarIdIndexRoute: typeof AuthenticatedCarsCarIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedCarsCreateRoute: AuthenticatedCarsCreateRoute,
  AuthenticatedRefuelsCreateRoute: AuthenticatedRefuelsCreateRoute,
  AuthenticatedRepairsCreateRoute: AuthenticatedRepairsCreateRoute,
  AuthenticatedCarsIndexRoute: AuthenticatedCarsIndexRoute,
  AuthenticatedRefuelsIndexRoute: AuthenticatedRefuelsIndexRoute,
  AuthenticatedRepairsIndexRoute: AuthenticatedRepairsIndexRoute,
  AuthenticatedCarsCarIdEditRoute: AuthenticatedCarsCarIdEditRoute,
  AuthenticatedRefuelsRefuelIdEditRoute: AuthenticatedRefuelsRefuelIdEditRoute,
  AuthenticatedRepairsRepairIdEditRoute: AuthenticatedRepairsRepairIdEditRoute,
  AuthenticatedCarsCarIdIndexRoute: AuthenticatedCarsCarIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
